trigger:
- master

pool:
  name: 'Default'

steps:

- task: AdvancedSecurity-Codeql-Init@1
  inputs:
    languages: 'javascript'

- task: UseDotNet@2
  displayName: 'Use dotnet 3.1'
  inputs:
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Use dotnet 6.0'
  inputs:
    version: 6.0.x


- task: UseDotNet@2
  displayName: 'Use dotnet 8.0'
  inputs:
    version: 8.0.x

- task: AdvancedSecurity-Codeql-Autobuild@1

- script: |
    npm install --global @cyclonedx/cyclonedx-npm
    npm i -g typescript ts-node
    npm install --production --unsafe-perm
    npm dedupe
  displayName: 'Run a multi-line script'

- task: AdvancedSecurity-Dependency-Scanning@1

- task: AdvancedSecurity-Codeql-Analyze@1

- task: AdvancedSecurity-Publish@1
  inputs:
    SarifsInputDirectory: '$(Agent.TempDirectory)/advancedsecurity.codeql/out'

- task: MicrosoftSecurityDevOps@1
  inputs:
    command: 'run'
    policy: 'microsoft'
  displayName: 'Run Microsoft Security DevOps'
